setwd("C:/Users/John/Desktop/RBook")
Veg <- read.table("Vegetation2.txt",header = TRUE)
head(Veg)
tail(Veg)
names((Veg))
str(Veg)
unique(Veg$Transect)
m <- mean(Veg$R)
m
m1 <- mean(Veg$R[Veg$Transect==1])
m1
m2 <- mean(Veg$R[Veg$Transect==2])
m3 <- mean(Veg$R[Veg$Transect==3])
m4 <- mean(Veg$R[Veg$Transect==4])
m5 <- mean(Veg$R[Veg$Transect==5])
m6 <- mean(Veg$R[Veg$Transect==6])
m7 <- mean(Veg$R[Veg$Transect==7])
m8 <- mean(Veg$R[Veg$Transect==8])
m12345678 <- c(m1,m2,m3,m4,m5,m6,m7,m8)
m12345678
avgm12345678 <- mean(m12345678)
avgm12345678
Me <- tapply(X=Veg$R,INDEX=Veg$Transect,FUN = mean)
mean(tapply(Veg$R, Veg$Transect, mean))
Me
Sd <- tapply(X=Veg$R,INDEX=Veg$Transect,FUN = sd)
Sd
Le <- tapply(X=Veg$R,INDEX=Veg$Transect,FUN = length)
Le
cbind(Me,Sd,Le)
sapply(Veg[,5:9],mean)
lapply(Veg[,5:9], mean)
sapply(cbind(Veg$R,Veg$ROCK,Veg$LITTER,Veg$ML,Veg$BARESOIL),mean)
sapply(data.frame(Veg$R,Veg$ROCK,Veg$LITTER,Veg$ML,Veg$BARESOIL), mean)
Z <- cbind(Veg$R,Veg$ROCK,Veg$LITTER)
head(Z)
colnames(Z) <- cbind("R","Rock","Litter")
head(Z)
summary(Z)
summary(Veg[ ,c("R","ROCK","LITTER")])
summary(Veg[,c(5,6,7)])
Deer <- read.table("Deer.txt",heade=TRUE)
head(Deer)
tail(Deer)
names(Deer)
str(Deer)
NoPerFarm <- table(Deer$Farm)
NoPerFarm
table(Deer$Sex,Deer$Year)
